version: "3.9"

services:
    laravellocal:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravellocal
        working_dir: /var/www//html
        volumes:
            - ./:/var/www/html
        ports:
            - 81:80
        environment:
            - VIRTUAL_HOST=laraveltest.local
            # Add other environment variables for your Laravel app here if needed
        networks:
            - inkamapp_local
# Docker network
networks:
    inkamapp_local:
        external: true

#volumes
volumes:
    dbdata:
        driver: local

