version: "3.9"

services:
    laravello:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravello
        working_dir: /var/www//html
        volumes:
            - ./:/var/www/html
        ports:
            - 81:80
        environment:
            - VIRTUAL_HOST=laravel.local
            # Add other environment variables for your Laravel app here if needed
        networks:
            - inkam_local
# Docker network
networks:
    inkam_local:
        external: true

#volumes
volumes:
    dbdata:
        driver: local

