version: "3.9"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    networks:
      - inkamapp_local
    ports:
      - "80:80"

    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

# Docker network
networks:
  inkamapp_local:
    external: true

